USE anayoga_anayoga;
/*M!999999\- enable the sandbox mode */ 
-- MariaDB dump 10.19-11.4.13-MariaDB, for Linux (x86_64)
--
-- Host: localhost    Database: anayoga_anayoga
-- ------------------------------------------------------
-- Server version	11.4.13-MariaDB

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*M!100616 SET @OLD_NOTE_VERBOSITY=@@NOTE_VERBOSITY, NOTE_VERBOSITY=0 */;

--
-- Current Database: `anayoga_anayoga`
--


--
-- Table structure for table `categories`
--

DROP TABLE IF EXISTS `categories`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `categories` (
  `catID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `title` varchar(255) DEFAULT NULL,
  `description` longtext DEFAULT NULL,
  `orderIndex` int(11) NOT NULL DEFAULT 0,
  PRIMARY KEY (`catID`)
) ENGINE=MyISAM AUTO_INCREMENT=23 DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `categories`
--

LOCK TABLES `categories` WRITE;
/*!40000 ALTER TABLE `categories` DISABLE KEYS */;
INSERT INTO `categories` (`catID`, `title`, `description`, `orderIndex`) VALUES (1,'Yoga Mat Bags','<font color=blue><b> *** Sorry!  We are currently sold out.  Custom orders welcome! <a href=http://www.anayoga.com/contact.php> Click here to order. </a>*** </font></b> <br> Beautiful handmade bags in a variety of high-quality fabrics.  Each bag is unique! ',2),
(8,'Other Yoga Accessories','One-of-a-Kind AnaYoga strap, blocks, meditation and relaxation supplies.',4),
(3,'Totes & Bags','Browse through a beautiful selection of totes, messenger bags, diaper bags and backpacks.  One-of-a-kind bags for you or that special someone!',6),
(4,'Jewelry','Unique handcrafted necklaces, earrings, bracelets, and more.',5),
(7,'*Clearance Items*','Join the <a href=\"contact.php\">AnaYoga.com Mailing List</a> to be notified of product updates and sales.  Clearance items do not last long! ',13),
(12,'Custom Orders','Can\'t find what you\'re looking for?  Consider customizing your order!',10),
(14,'Gift Bags','The next time you give someone a gift, give a gift to the environment as well with these reusable cloth gift bags.<i>  A variety of sizes and fabrics are available.  Those shown here are just a sampling!</i> All prices include shipping to the US/Canada.',7),
(17,'Fabric Selection','Here is a current sampling of fabrics and trims  available for custom orders.  Please note:  In order to continue making one-of-a-kind items, I purchase a wide variety of fabric in small quantities.  All fabrics shown here are available in *limited* amounts only.  Can\'t decide which fabric you\'d like?  I would be happy to suggest fabrics for a given project, <a href=http://www.anayoga.com/contact.php>just ask!</a>',11),
(18,'Gallery','Sit back and take a few minutes to browse through a selection of AnaYoga Originals and custom creations which I have handcrafted for clients in the past.  <b>Everything you see here is happily residing with a new owner and is no longer available for purchase.  You can place your custom order by using the <a href=http://www.anayoga.com/contact.php>\"Contact Me\"</a> link at the top of the page.</b>',12),
(21,'Custom Gift Baskets','Can\'t decide on the perfect gift?  How about a little of everything!  Great prices for exquisite custom-made baskets.  ',9),
(22,'Gift Certificates!','The perfect gift!  Gift certificates are available in any amount you wish to give.  ',8);
/*!40000 ALTER TABLE `categories` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Table structure for table `options`
--

DROP TABLE IF EXISTS `options`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `options` (
  `id` int(10) unsigned NOT NULL DEFAULT 0,
  `name` char(50) DEFAULT NULL,
  `value` char(50) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `options`
--

LOCK TABLES `options` WRITE;
/*!40000 ALTER TABLE `options` DISABLE KEYS */;
/*!40000 ALTER TABLE `options` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Table structure for table `products`
--

DROP TABLE IF EXISTS `products`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `products` (
  `prodID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(30) DEFAULT NULL,
  `price` double DEFAULT NULL,
  `description` longtext DEFAULT NULL,
  `imgFileName` varchar(255) DEFAULT NULL,
  `imgDetailFileName` varchar(255) NOT NULL DEFAULT '',
  `featured` tinyint(4) NOT NULL DEFAULT 0,
  `category` int(11) NOT NULL DEFAULT 0,
  `orderIndex` int(11) NOT NULL DEFAULT 99,
  PRIMARY KEY (`prodID`)
) ENGINE=MyISAM AUTO_INCREMENT=373 DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `products`
--

LOCK TABLES `products` WRITE;
/*!40000 ALTER TABLE `products` DISABLE KEYS */;
INSERT INTO `products` (`prodID`, `name`, `price`, `description`, `imgFileName`, `imgDetailFileName`, `featured`, `category`, `orderIndex`) VALUES (150,'\"Daisy\" Tote Bag',0,'<font color=red> This item has been purchased.  Use the \"Contact Me\" link at the top right of this page to place a custom order</font>.  Soft brushed cotton tote. Features pretty daisy florals on a light blue background. 100% cotton lining in matching sky blue. This bag is lined with interfacing, giving a sturdy form to the bag and allowing it to stand on its own. Measures approximately 12\" long x 11\" high x 3\" wide. Each handle measures 17\" long (end-to-end).','BluedaisyTote.jpg','bluedaisyCU.jpg',0,18,5),
(91,'Hemp Yoga Strap',14,'Use this one-of-a-kind AnaYoga strap to help ease yourself further into each stretch. A unique patent-pending design!  Made from beautiful unbleached hemp, the wide strap is constructed to ensure comfort and durability. Rings allow you to get a better hold of the strap, so you can focus on each posture. The adjustable buckle makes this strap functional for all levels of flexibility, and lets you easily vary the length for smooth transition between postures. Designed and constructed by myself for my students and yoga practitioners everywhere. Measures approximately 32” and expands to 53” (measured from ring to ring). Custom sizes available, please ask.','yoga strap1.jpg','',0,8,2),
(203,'\"Sunrise Sunset\"',0,'<font color=red> This bag has been purchased.  Use the \"Contact Me\" link at the top right of this page to place a custom order</font>.  Soft brushed poly-cotton blend yoga bag. This bag is made from upholstery grade fabric that is both strong and beautiful. The fabric feels velvety to the touch. It features a subtle leaf and geometric pattern on an earthy, safron-coloured background. The strap is a soft and thick 100% unbleached cotton that is carefully hand-braided. The drawstring at the top is made from 100% unbleached hemp, also hand-braided and decorated with matching beads. The easy-to-use black pull cord keeps all your yoga gear secured inside the bag. This bag is roomier than most other yoga bags, and is wide enough to fit a standard sticky mat, blocks, strap, and other small belongings such as a wallet, bottle of water, etc. It measures approximately 13” x 27” with a 27” long handle. ','Sunrise.jpg','sunriseCU.jpg',0,18,3),
(147,'Indigo Paisley',0,'<font color=red> This bag has been purchased.  Use the \"Contact Me\" link at the top right of this page to place a custom order</font>. This bag is sure to get some attention! It is made of lightweight satin in a rich shade of indigo, and features a flowing paisley design. It feels soft to the touch, and drapes beautifully. This bag requires gentle care and is intended for the yogi who appreciates delicacy. But don’t be mistaken, it is strong enough to carry all your yoga gear. The strap is a soft and thick 100% unbleached cotton that is carefully hand-braided. The drawstring at the top is made of 100% unbleached hemp, also hand-braided and decorated with matching beads (please see detailed photo). The easy-to-use pull cord keeps all your yoga gear secured inside the bag. This bag is roomier than most other yoga bags, and is wide enough to fit a standard sticky mat, blocks, strap, and other small belongings such as a bottle of water, wallet, etc. It measures approximately 12” x 27” with a 27” strap.','IndigoSatin.jpg','indigosatinCU.jpg',0,18,3),
(182,'Amber with Charm (SOLD)',18,'<font color=red>Sorry, this necklace has been purchased.  Please contact me for custom-made pieces.</font>This necklace features honey and amber coloured glass beads strung along a wire.  A small matching stone encased within a wire cage hangs delicately at the bottom.  The lobster claw clasp and loop are securely attached to a metal wire that measures approximately 20\" long.   Shipping to Canada/continental USA included in price.  Will ship worldwide!','amber20001.JPG','',0,4,15),
(25,'\"Crimson Leaves\"',0,'<font color=red>Sorry, this yoga bag has been purchased.  Use the \"Contact Me\" link at the top right of this page to place a custom order.</font> </font> Another stunning bag, this one is made of 100% polyster.  Strong and flowing, it features a pretty leaf pattern on a deep crimson background.  The strap is a soft and thick 100% unbleached cotton that is carefully hand-braided.  The drawstring at the top is made of 100% unbleached hemp, also hand-braided and decorated with matching beads.  The easy-to-use pull cord keeps all your yoga gear secured inside the bag.  This bag is roomier than most other yoga bags, and is wide enough to fit a standard sticky mat, blocks, strap, and other small belongings such as a bottle of water, wallet, etc.  It measures approximately 13” x 28”with a 27” strap.','AnaYoga012.jpg','AnaYoga12b.jpg',0,18,4),
(345,'\"Metal\" Kanji Necklace',18,'Place description here. \"Metal\" in the Elemental series of one-of-a-kind, handcrafted necklaces. This necklace features the kanji symbol for \"metal\", which is embraced on either side by a string of hematite beads. Hematite is believed to impart good health and positive energy. Measures approximately 18\" in length, with a 1\" extension chain secured with a lobster claw clasp and hook. See others in this series, including \"earth\", \"water\" and \"wood\".','metal.JPG','metalCU.JPG',0,4,10),
(28,'\"Showers of Flowers\"',0,'<font color=red>Sorry, this bag has been purchased.  Use the \"Contact Me\" link at the top right of this page to place a custom order</font>  This yoga bag is made of a poly-cotton blend fabric, featuring a pretty, multi-coloured floral pattern on a soft beige background.  It is strong and functional.  The strap is a soft and thick 100% unbleached cotton that is carefully hand-braided.  The drawstring at the top is made of 100% unbleached hemp, also hand-braided and decorated with matching beads.  The easy-to-use pull cord keeps your yoga gear secured inside the bag.  This bag is roomier than most other yoga bags, and is wide enough to fit a standard sticky mat with room to spare.  It measures approximately 11” x 28” with a 30” strap.','AnaYoga015.jpg','AnaYoga15b.jpg',0,18,3),
(124,'Hemp and Paisley',0,'<font color=red> This bag has been purchased.  Use the \"Contact Me\" link at the top right of this page to place a custom order</font>. This bag is made from natural, unbleached hemp fabric. It features a bold, paisley-pattern trim with gold threading. Hemp is an extremely strong and durable fabric. The handle is made of a thick and soft 100% unbleached cotton that is carefully hand-braided. The drawstring is made from 100% unbleached hemp twine that has also been hand-braided, and features an easy-to-use pull cord and matching beads. This bag measures approximately 9” x 26” with a 27” strap.','HempYogaTote 019.jpg','HempYogaCU.jpg',0,18,3),
(178,'The Instructor\'s Tote',0,'Durable construction, attractive fabrics, practical design.  Custom-made for the yoga instructor who needs to carry a lot of equipment from class to class.  This bag is large enough to carry 4 standard yoga mats, with room to spare for blocks and other equipment.  It comes with a separate, matching drawstring pouch to place your shoes, wallet and other small items which tend to slip to the bottom of conventional bags.  Wide nylon straps help distribute the heavy load on your shoulders, while the sleek construction makes this bag completely portable and storable.  Contact me with colour and fabric choices.  Ready for shipping within 5-10 days of placing order. <font color=red> (Please note: Butterfly tote pictured has been purchased.  Many other fabric choices are available.  Contact me for more info). </font>','yogatoteBFLY.jpg','yogatoteIN.jpg',0,18,2),
(169,'Therapeutic Heat/Cool Pack',18,'This pack is made of unbleached hemp, with a decorative lavender coloured trim. The pack contains 100% organic linseed, and can be used cool (store in fridge) or warm (microwave). Linseed, aka “flax seed”, is filled with natural oils and maintains its temperature longer than traditional rice-filled packs. The cover is removable and washable, and features a loop-and-hook (tm “Velcro”) fastener at one end. Measures approximately 4.5” x 19”, and wraps comfortably behind your neck to help relieve tense muscles and headaches. <font color=red> This particular fabric combination has been purchased.  Many others available!</font>','heatpack.jpg','heatpackCU.jpg',0,8,4),
(142,'Lavender Scented Eye Pillow',14,'Use this eye pillow to help soothe and comfort sore, tired eyes. Let the gentle weight of linseeds rest on your eyes during relaxation or meditation, and allow the soothing scent of lavender to clear and calm your mind. The cover is made of hemp on one side, and a cool satin on the other. It is removable and washable, with loop-and-hook (tm “Velcro”) fasteners at one end. The pouch is filled with 100% organic linseed, and pure, fragrant lavender buds.  For those with sensitivities, the lavender buds can be excluded upon request.','eyepillow.jpg','eyepillowCU.jpg',0,8,5),
(213,'\"Green Beauty\" (SOLD)',15,'<font color=red>Sorry, this necklace has been purchased.</font> <p> Even more stunning in person! You have to see and feel this necklace to appreciate it. The heavy and cool sensation of the stones can not be seen in the photo. This necklace features a mixture of green semi-precious stones of various shapes and sizes arranged to create a beautiful necklace. This necklace can be worn casual with a t-shirt, or dressed up as an accent for a special occasion. A small matching stone encased within a wire cage hangs delicately at the bottom. <p>The lobster claw clasp and loop are securely attached to a metal wire that measures approximately 20\" long.  ','greenbeauty0001.JPG','',0,7,5),
(64,'Custom Orders',0,'I do custom orders.  Please <a href=\"contact.php\">contact me </a>for more information.  Previous custom orders for clients have included specialized sporting bags (such as the kendo martial arts bag pictured here), tote and gift bags with personalized photos, custom-sized yoga bags, straps, blocks and clothing for all ages and sizes.','AnaYoga 036.jpg','',0,12,1),
(352,'\"Fire\" Kanji',0,'<font color=red>Sorry, this item has been purchased.</font> \"Fire\" in the Elemental series of one-of-a-kind, handcrafted necklaces. This necklace features the kanji symbol for \"fire\", which is embraced on either side by a string of high-quality beads which flicker with rich red, yellow and orange tones. Measures approximately 18\" in length, with a 1\" extension chain secured with a lobster claw clasp and hook. ','firekanji0001.JPG','firekanji0002.JPG',0,18,11),
(351,'\"Love\" Kanji Necklace',18,'\"Love\" in the Elemental series of one-of-a-kind, handcrafted necklaces. This necklace features the kanji symbol for \"love\", which is embraced on either side by a string of high quality, red glass beads. Measures approximately 18\" in length, with a 1\" extension chain secured with a lobster claw clasp and hook. ','lovekanji0001.JPG','lovekanji0002.JPG',0,4,5),
(79,'\"Golden Leaves\"',0,'<font color=red>Sorry, this bag has been purchased.</font> This bag is one of my absolute favourites. It is made from a golden sateen upholstery grade material. It is strong and beautiful, featuring small, golden leaves delicately raised above the fabric. The strap is a soft and thick 100% unbleached cotton that is carefully hand-braided. The drawstring at the top is made of 100% unbleached hemp, also hand-braided and decorated with matching beads. The easy-to-use golden pull cord keeps all your yoga gear secured inside the bag. This bag is roomier than most other yoga bags, and is wide enough to fit a standard sticky mat with room to spare. It measures approximately 11” x 27” with a 27” strap.','AnaYoga 011.jpg','AnaYoga 11b.jpg',0,18,3),
(200,'Nylon Yoga Strap',14,'Use this one-of-a-kind AnaYoga strap to help ease yourself further into each stretch. A unique, patent-pending design!  Wide nylon construction ensures comfort and durability. Rings allow you to get a better hold of the strap, so you can focus on each posture. The adjustable buckle makes this strap functional for all levels of flexibility, and lets you easily vary the length for smooth transition between postures. Designed and constructed by myself for my students and yoga practitioners everywhere. Measures approximately 20” and expands to 33” (measured from ring to ring). Custom sizes also available, please ask.','nylonstrap.jpg','nylonstrapCU.jpg',0,8,3),
(367,'\"Blue Bird\" necklace',20,'This little birdie is the bringer of good news!  Do you have some exciting news to share with a loved one?  Celebrating a special event?  This little bird will carry your message in style, specially gift-wrapped and personalized with a note of your choice!  \r\n<p>Handcrafted using high quality beads on a strong wire, securely attached to an elegant toggle clasp which features a heart motif. The necklace, measured from end-to-end is approximately 20\" long. <p>\r\nShipping to Canada/continental USA included in price. \r\n','neckbird.JPG','neckbirdCU.JPG',0,4,3),
(88,'Wooden Yoga Blocks',15,'<font color=blue>Sorry, these yoga blocks are currently out of stock.  New, improved blocks will soon be available!  <a href=http://www.anayoga.com/contact.php> Join the mailing list here</a> to be notified of product updates!</font><p>These solid wood blocks are made of cedar, a very strong and lightweight material. The wood for these blocks have been harvested from ecologically intact forests (NO CLEARCUTTING!). Furthermore, these blocks have NOT been chemically treated. They have been hand-sanded for a smooth finish. <p>Because these blocks have not been treated with chemicals or paint, the following care is recommended: *Store away from direct sunlight *Avoid exposure to drastic changes in humidity *Minor \"imperfections\" such as knots are a beautiful and natural characteristic of wood. Such knots may be present in the finish of your block so as not to waste any part of the tree. Standard size available: 3x6x9\". Custom sizes can also be ordered. <font color=red>$15 each or $28 a pair. Shipping extra.</font>','yogablocks.jpg','',0,8,6),
(359,'\"Sakura\"  Bag (SOLD)',35,'<font color=red>Sorry.  This one-of-a-kind bag has been purchased.</font> <p>Sakura, the Japanese word for \"Cherry Blossom\" is a symbol of peace and friendship.  \"Sa\" means god of the paddies and \"Kura\" means the place of the God. \"SAKURA\" is a place where the god of the paddies is present. From ancient times, people have gathered under blossoming cherry trees to celebrate spring and life. <p>This bag is all-natural jute.  I have painted cherry blossoms on the front, along with the kanji symbol for sakura.  This bag measures approx. 14\"x11\" with a WIDE 8\" base, very roomy! Perfect for trips to the beach, or as a craft/knitting bag! The handles are wooden, and reminiscent of the famous pagodas in Japan.<p>\r\n\r\nThe trim around the bag has been adorned with a pretty cherry and leaf motif.  The special fabric paint has been \"set\" and will not run or smudge.  <p>FREE SHIPPING TO CANADA/US!','sakura1.jpg','sakura2.jpg',0,3,13),
(154,'\"Libra\" Necklace',0,'<font color=red>Sorry, this item has been purchased.  Use the \"Contact Me\" link at the top right of this page to place a custom order</font> <font color=blue>Libra (September 24-October 23) </font>This necklace is \"Libra\" in a series of fun zodiac charm necklaces. The necklace features a high-quality pewter alloy \"Scales\" on a metal wire necklace. The charm has the engraved zodiac symbol on both sides! Please see the detailed photo on right to get a closer look. Lobster claw clasp and hook attach the ends. Measures approximately 18\" long. <font color = red>Regular Price: $19.99</font>','libra0001.JPG','libra0002.JPG',0,18,6),
(208,'Batik Yoga Bag',0,'<font color=red> This bag has been purchased.  Use the \"Contact Me\" link at the top right of this page to place a custom order</font>.  Beautiful batiks! 100% cotton with blending shades of gorgeous colour. Fully lined (see photos) and matching detailed trim on strap and drawstring. Carefully topstitched for durability and for that professionally tailored look! This bag is wide enough to fit a standard yoga mat, with room to spare. Measures approximately 12\"x30\", with a drawstring and clasp closure to keep your items secure. This particular bag is sold, however I will personalize your bag with your colour preferences at no extra charge. ($39.99 each)','batikyogabag.jpg','batikyogabagCU.jpg',0,18,3),
(347,'\"Sandstone\" Hemp',8,'<font color=red>Regular Price $10, Clearance Price $8, shipping to US/Canada included!</font><p>This necklace has been handcrafted from 100% hemp twine, and adorned with \"sandstone\" beads. Simple, crisp and neutral, this 16\" choker-style necklace is sure to complement any outfit. ','sandyhemp.JPG','sandyhempCU.JPG',0,7,15),
(348,'\"Voodoo\" Hemp',8,'<font color=red>Regular price $10, Clearance price is $8, shipping to US/Canada included!</font><p> This 16\" choker style necklace has been carefully handcrafted, one knot at a time, using 100% hemp twine. It features five high quality beads with intricate markings and a ball-and-loop closure. ','voodoo.JPG','voodooCU.JPG',0,7,16),
(356,'\"Moda\" Tote Set (SOLD)',45,'<font color=blue>Sorry, this item has been purchased.</font> This tote set is one-of-a-kind!  It has been handcrafted using 100% cotton buttery-soft velour fabric in cool blue stripes. Take a peek inside this bag and you\'ll see a 100% cotton print featuring stylish fashionistas sipping on coffee, chatting on the phone, and taking their pooches on a stroll.  This luxurious soft tote has a handy key clip and a magnetic snap closure to keep your belongings secure.  This set also includes a matching zippered makeup pouch! The tote measures a roomy 13\"x11\"x4\" with a 23\" long strap, and the pouch measures approximately 6\"x7\".  ','bagset1.jpg','bagset7.jpg',0,3,4),
(115,'\"Checkered\" Tote',38,'This tote is truly unique. It is made of a rich brown and black checkered fabric with detailed stitching, creating a slightly raised, quilted effect. The exterior is a poly blend that catches the light and shimmers ever so slightly. The lining is a beautiful copper satin fabric, and includes a small inner pocket. This bag is lined with lightweight interfacing, lending the bag support while allowing a fluid soft movement. Measures approximately 12\" long x 11\" high x 3\" wide. Each handle measures 17\" long (end-to-end).  Shipping to Canada/continental USA included in price. Worldwide shipping is also available!','checkTote.jpg','',0,3,4),
(117,'\"Blue Orient\"',0,'<font color=red>Sorry, this item has been purchased</font>  Made from 100% cotton, this blue tote has a gorgeous golden oriental-inspired filigree pattern throughout. Open the bag and you will see a beautiful royal purple lining, as well as a small inner pocket. The contrast between the blue and deep purple is eye-catching, and is also apparent on the underside of each handle. Please see the detailed photo for a close-up of this tote! This bag is lined with interfacing, lending the bag support so that it can stand on its own. Measures approximately 12\" long x 11\" high x 3\" wide. Each handle measures 17\" long (end-to-end).','bluebag.jpg','insideblue.jpg',0,18,5),
(139,'Diaper Bag & Pad',70,'This is a diaper bag I custom-designed for a client. It consists of one large main compartment, a small inner pocket, two outer sippy-cup/bottle pockets with elasticized tops, and a key ring/pacifier loop at the top of the bag to keep these smaller items from getting lost at the bottom. The matching change pad has a removable, machine-washable cover encasing a waterproof padding. Each bag has interfacing to lend support and strength to the bag. I make these diaper bags one at a time, to your specifications for fabric and features. Please use the \"Contact Me\" link to place your order, or to have any questions answered.  Shipping to Canada/continental USA included in price. Worldwide shipping is also available!</font>','toiledipebag2.JPG','',0,3,2),
(170,'Bolsters',25,'These bolsters are handmade, and can be used to support the neck, lower back or knees during reclined postures, or as a decorative accent in your home! Made with a breathable and durable hypo-allergenic poly fill, enclosed in 100% unbleached hemp. The luxurious satin cover is removable and washable, and is available in your choice of fabrics. Contact me for other fabrics, I\'d be happy to find the perfect shade for you. Measures approximately 6\" diameter x 17\" length.  Sold individually.','bolsters.jpg','bolsters2.jpg',0,8,1),
(146,'Turquoise Necklace',0,'<font color=red>This particular necklace has already been purchased.  Similar jewelry can be custom made using the same stones you see here.  Use the \"Contact Me\" link at the top right of this page to order. </font> Beautiful turquoise glass beads, delicately interspersed by light blue glass beads that catch the light.  This necklace has a gentle weight to it, and caresses the neck with a cool stone sensation.','torquoiseneck0001.JPG','',0,18,16),
(181,'\"Silver Belle\" Tote',0,'<font color=red> This item has been purchased.  Use the \"Contact Me\" link at the top right of this page to place a custom order</font>. This tote is made of a beautiful silver satin material featuring a delicate black intertwined floral pattern throughout. Inside the bag is a matching grey fabric, and a small inner pocket. This bag is lined with interfacing, lending the bag support so that it can stand on its own. Measures approximately 12\" long x 11\" high x 3\" wide. Each handle measures 17\" long (end-to-end).','silverbag.jpg','insilver.jpg',0,18,5),
(184,'\"Golden Locket\" Necklace',0,'<font color=red>This necklace has been purchased.</font>  This necklace features a large 1.5\" golden locket which opens and closes with room inside for 2 photos.  The locket is adorned with swirling golden details and 7 sparkling gems. The cord is a strong black rope with a clasp closure securely attached. The necklace measures approximately 16\" in length.','blkchokerLocket0001.JPG','',0,18,6),
(189,'\"Honey\" Beads',0,'<font color=red>Sorry, this item has been purchased</font>  This \"sweet\" little necklace features high quality honey and amber-coloured glass beads strung along a metal wire. The lobster claw clasp and loop are securely attached to a metal wire that measures approximately 20\" long.','necklaceamber0001.JPG','',0,18,17),
(214,'Sling Bag',0,'<font color=red> This item has been purchased.  Use the \"Contact Me\" link at the top right of this page to place a custom order</font>. A totally new and unique design!  Extra-wide strap for comfort, deep pouch for carrying everything you\'ll need, and a beautiful floral print that is sure to get noticed!  This bag is fully lined, and has an inner pocket for small items that tend to slip towards the bottom of your bag.  For more photos of this bag, contact me and I will e-mail them to you!  ','slingbag.jpg','slingbagside.jpg',0,18,5),
(224,'Messenger Bag',0,'<font color=red> This item has been purchased.  Use the \"Contact Me\" link at the top right of this page to place a custom order</font>.  A beautiful, soft faux suede messenger-style bag.  Featuring a luxurious copper-coloured satin lining and two outer pockets.  ','fauxsuedeMB.jpg','fauxMBopenflap.jpg',0,18,5),
(225,'Messenger Bag',0,'<font color=red> This item has been purchased.  Use the \"Contact Me\" link at the top right of this page to place a custom order</font>. This bag is one of my favourites.  Made from 100% cotton, the outside of the bag is a soft blue corduroy.  Peek inside, and you will see an elegant toile lining, also 100% cotton.  This bag measures approximately 11\"x15\"x4\", with a 45\" long strap.  The strap is just under 2\" wide, so it sits comfortably on one shoulder or across your chest.  One outer pocket runs flush with the front of the bag, making this bag sleek, stylish and functional!  ','toilebluecord.jpg','toilebluecordIN.jpg',0,18,5),
(226,'Messenger Bag',0,'<font color=red> This item has been purchased.  Use the \"Contact Me\" link at the top right of this page to place a custom order</font>.  Soft 100% cotton corduroy exterior, and an earthy striped interior.  This one-of-a-kind bag features one outer pocket, and one large compartment to hold all your items. Beautifully soft to the touch, with a wide and comfortable strap.    ','blackMB.jpg','blackMBin.jpg',0,18,5),
(230,'AnaYoga Custom Totes!',35,'<font color=blue>You be the designer and I\'ll do the rest! </font> Each tote comes fully lined, with a small inner pocket.  Need more features?  Extra pockets?  Water bottle holder?  Change pad?  Magnetic snap or zipper closure?  Let me know and I will customize your bag to your exact specifications.  <a href=http://www.anayoga.com/contact.php> Click here to place your order! </a>Prices start at just $35, shipping to Canada/continental USA included!  ','toiletote.jpg','dottytote.jpg',0,3,1),
(232,'\"Dragon, the Protector\"',0,'<font color=red> This item has been purchased.  Use the \"Contact Me\" link at the top right of this page to place a custom order</font>.  In China, the mythological symbol of the Dragon dates back to 3000 BC.  Dragons were believed to be protectors and to ward off evil spirits.  This necklace features 5 unique beads from the orient, flanked on each end by 2 red dragons.  In numerology, a life path \"5\" is a person who is very versatile and adventurous.  This necklace is a perfect gift for that free-spirited, adventurous friend...who could sometimes use a little friendly protection of the dragon-kind!  This necklace measures approximately 5\" in diameter, and is mounted on a tension wire which expands and contracts to fit around the neck.  ','tensionOrientNkl0001.JPG','tensionOrient0001.JPG',0,18,17),
(234,'100% Cotton - Blue Batik',0,'Beautiful 100% cotton batik fabric with floral motif throughout.  Softly blending shades of blue.  ','bluebatik.jpg','',0,17,4),
(236,'Cotton/Poly Blend - Blue Dane',0,'Cotton/Poly Blend.  Dark blue background featuring dots (\"stippling\") and a flowing floral pattern in a blue-white print.','blue and white0001.JPG','',0,17,22),
(238,'Children\'s Iron-Ons/Appliques',0,'Fun selection of small (approx. 1.5\") iron-on appliques.  Choose from Snowman, Bear, Santa, Whale, Elephant, Fish, Reindeer, Stocking, and Tree.','emb0002.JPG','',0,17,38),
(239,'Blend - Little Roses',0,'Very soft and flowing woven fabric, featuring small rosebuds on a dark burgundy background.  Fabric has a slight sheen to it, not visible in photo.','epFlowers0001.JPG','',0,17,23),
(241,'Blend - India Paisley',0,'This fabric will work beautifully lining the inside of a tote, or on the outside of a yoga mat bag.  Dark, earthy brown paisley swirls.  ','indiapaisley0001.JPG','',0,17,24),
(266,'100% Cotton - Clovers',0,'100% cotton, green clovers on a black background.  There are golden highlights throughout, making this fabric unique!  Not just for St.Patrick\'s Day, we could all use a little \"luck of the Irish\" on any day!','clover.JPG','',0,17,31),
(244,'Blend - Silver Filigree',0,'This will make an elegant handbag clutch or drawstring purse.  Silver woven fabric with a very slight stretch, with a raised \"swirling\" filigree textured throughout.  Catches the light beautifully.','silverswirl0002.JPG','',0,17,23),
(245,'Unbleached Hemp and Cotton',0,'Unbleached hemp, cotton or hemp/cotton blends available.  This fabric is just as named, completely unbleached.  Variety of thicknesses/weaves available (such as muslin, canvas, etc).  ','ubcotton0001.JPG','',0,17,1),
(246,'Polyester - Soft Pink Floral',0,'Polyester/Crepe.  Soft pink background with small white florals throughout.  Very feminine and flowing.','soft pink floral0001.JPG','',0,17,27),
(247,'Blend - Retro Velour',0,'One of my all-time favourite fabrics!  This picture does not do justice to the colours in this material, nor to the soft and luscious feel of the velour.  The velour is a poly-cotton blend, featuring a geometric \"retro\" pattern throughout.  ','velour swatch0001.JPG','',0,17,26),
(248,'100% Cotton - \"Burberry\" Plaid',0,'100% cotton, brushed flannelette.  Soft and classic.','burberry0001.JPG','',0,17,8),
(249,'100% Cotton - Butterfly Batik',0,'100% cotton. This beautiful fabric is so soft to the touch, and features batik butterflies on a dark blue/indigo background.','butterflybatik0001.JPG','',0,17,5),
(251,'100% Cotton - Dynasty Green',0,'100% Cotton in a stunning Dynasty pattern, green with hints of gold.','dynastyGreen0001.JPG','',0,17,9),
(254,'Cotton/Poly Blend - Greenleaf',0,'A simple and pretty material.  Soft mossy green background with small white floral pattern throughout.','Greenleaf0001.JPG','',0,17,18),
(255,'100% Cotton - Indigo Bindigo',0,'100% cotton, soft and pretty.  Intertwined white florals on a dark purple/indigo background.  ','indigobindigo0001.JPG','',0,17,11),
(256,'Cotton/Poly Blend - Kanji',0,'Light and flowing material features kanji characters (depicting a poem about the countryside) on a rich brown background.','kanjibrown0001.JPG','',0,17,20),
(257,'100% Cotton - Blue Moon',0,'100% cotton.  This medium blue fabric features the moon and stars, scattered throughout.','moonshine0001.JPG','',0,17,12),
(259,'Cotton/Poly Blend - Silver Sta',0,'Fun and celestial!  Sparkling silver stars on a maroon background.','silverstars0001.JPG','',0,17,19),
(262,'100% Cotton - TieDye Batik',0,'100% Cotton.  So soft!  A gorgeous blend of colours, gently fading in and around each other.  I had one client describe her bag made from this material as having \"peacock-like feathers\".  One of my favourite fabrics!','tiedyebatik0001.JPG','',0,17,6),
(265,'Black Hemp or Cotton',0,'Hemp/cotton black canvas, or 100% cotton (various thicknesses available).','blackhemp0001.JPG','',0,17,2),
(267,'100% Cotton - Floral Corduroy',0,'100% cotton, and very soft!  Thin wale corduroy featuring a pretty floral print on an off-white background.','floralcord0001.JPG','',0,17,32),
(268,'100% Cotton - Green Dots',0,'100% cotton, lightweight.  Perfect for lining a bag.  \"Retro\" geometric dots print on a green background.','greengeo.JPG','',0,17,33),
(270,'100% Cotton - Jungle Animals',0,'100% cotton.  What a fun print!  Features zebras, elephants, tigers, and more!  Bold colours on a black background.  Perfect for kids\' totes or the young-at-heart.','junglekid0001.JPG','',0,17,35),
(272,'100% Cotton - Violets',0,'100% cotton.  Violets, in a soft mauve colour.  Pretty silver accents throughout make this fabric unique and pretty!','purplefloral0001.JPG','',0,17,37),
(281,'\"Tropical Breeze\"',0,'<font color=red>This item has been purchased.</font> Close your eyes and feel the warmth of the sun against your skin, the sounds of the ocean waves along the beach and the gentle touch of a tropical breeze.  This yoga bag will carry your yoga mat in style, and carry <b>you</b> away to a place of serenity and calm with beautiful palm trees swaying in the breeze.  This yoga bag is the perfect way to carry your yoga gear, with a large main compartment to carry more than just your mat!  Spacious drawstring opening, 2 pockets, a place to clip your keys, a wide strap for comfort, and fully lined with coordinating fabric.  Measures approximately 30\" high x 14\" wide x 8\" base.  Second photo shows inside of the bag.','tropicalbreeze.jpg','tropicalbreezeCU.jpg',0,18,2),
(274,'\"Phoenix Sun\"',0,'<font color=red>Sorry, this item has been purchased</font>This necklace was inspired by a recent trip to sunny Phoenix Arizona.  The sun charm is STERLING SILVER, and a symbol of energy and life.  The spherical hematite beads are claimed to impart good health and vitality to those who wear it.  This necklace is handcrafted, using high quality beads on a tension mounted wire.  Measures approximately 4.5\" in diameter as shown, and expands to fit around the neck.  The sun charm measures approximately 3/4\" in diameter.','phoenixSun.JPG','phoenixSunCU.JPG',0,18,15),
(275,'\"Om Land\"',0,'<font color=red>Sorry, this item has been purchased</font>\"OmLand\" features a STERLING SILVER Hindu \"Om\" symbol, gently caressed on either side by a series of copper-brown beads (symbolizing the Earth) and dark green beads (symbolizing the life that comes from within the Earth).  Handcrafted using high quality beads on a tension mounted wire. Measures approximately 4.5\" in diameter as shown, and expands to fit around the neck. The silver Om charm measures approximately 3/4\" in width and 1\" in height.','multiOm.JPG','multiOmCU.JPG',0,18,14),
(276,'Hematite Om',28,'Simple and stunning.  This necklace features a STERLING SILVER Hindu \"Om\" symbol on a string of hematite beads, with green accents near the charm.  Hematite is believed to impart a positive healing energy to those who wear it.  Handcrafted using high quality beads on a strong wire, securely attached to a lobster clasp and loop, with an extension chain to let you choose the length.  The necklace, measured from end-to-end is approximately 18\" long. The silver Om charm measures approximately 3/4\" in width and 1\" in height.   Shipping to Canada/continental USA included in price.  Will ship worldwide!','hematiteOm.JPG','hematiteOmCU.JPG',0,4,4),
(278,'Sterling Silver Butterfly (SOL',28,'<font color=red>Regular $45.  Special clearance price $28! Shipping to Canada/continental USA included in price! </font> <p>Second in the series of STERLING SILVER jewelry.  This necklace features an 18\" long sterling silver chain, and an elegant sterling silver butterfly.  The butterfly\'s wings are adorned with sparkling clear gems, and the delicate details of the charm add character and quality to this unique piece.  \r\n\r\n<p>This necklace will arrive beautifully displayed in a burgundy necklace box, ready for gift giving or wear.  ','silverbfly0001.JPG','silverbflyCU0001.JPG',0,7,3),
(279,'Diaper Backpack & Pad',70,'This backpack is a sample of what I can make for you.  The bag was custom-made for a client wishing to have a roomy bag to carry her toddler\'s diapers, clothes and snacks, but without all the bulk!  2 sippy cup holders on the front of the bag leave the inside of the bag available for the matching change pad and more! The bag also features a small inner pocket for keys and small items, a drawstring top and a magnetic snap closure!  Fully lined.  The diaper pad features a removable cover, and folds up neatly to fit inside the bag.  All machine washable!  Shipping to Canada/continental USA included in price. Worldwide shipping is also available!','laurelsbag1.jpg','laurelsbag2.jpg',0,3,3),
(280,'Hemp Purse',0,'<font color=red> This bag has been purchased.  Use the \"Contact Me\" link at the top right of this page to place a custom order</font>. This hemp purse is simple and stylish.  It can be used as a casual accessory or on a special night out.  The outer material is 100% hemp in a thick black canvas.  The inside of the bag is lined with a luxurious 70% hemp - 30% silk in a soft blue.  There is a magnetic snap closure, and a pretty butterfly detail on the front flap.  The strap is long enough to wear on your shoulder so the bag sits just under your arm, or to be held in your hand without having the bag drag near the ground. Measures approximately 11\"x6\"x2\".  Simply perfect!','barbpurse.jpg','barbpurseIN.jpg',0,18,5),
(283,' \"Aloha\" (SOLD)',28,'<font color=red> Regular $38, CLEARANCE price $28 with shipping to Canada/continental USA included!</font><p>  This yoga bag features a 100% cotton exterior, with swaying palm trees and cascading waterfalls.  A vacation in a bag!  This yoga bag is the perfect way to carry your yoga gear, with a large main compartment to carry more than just your mat!  <p>Spacious drawstring opening, 2 pockets, a place to clip your keys, a wide strap for comfort, fully lined with coordinating fabric and finished off with decorative beading.  Measures approximately 30\" high x 14\" wide x 8\" base.  Second photo shows inside of the bag.','aloha.jpg','alohaCU.jpg',0,7,2),
(284,' \"Violet Dusk\" (SOLD)',38,'Sorry, this item has been purchased.  Please contact me for custom orders.  Shipping to Canada/continental USA included in price. Worldwide shipping is available!  You have to touch and see this bag to believe it.  Made from a soft and luscious velvety material with a subtle floral motif throughout.  This yoga bag is the perfect way to carry your yoga gear, with a large main compartment to carry more than just your mat! Spacious drawstring opening, 2 pockets, a place to clip your keys, a wide strap for comfort, fully lined with coordinating fabric and finished off with decorative beading. Measures approximately 30\" high x 14\" wide x 8\" base. Second photo shows inside of the bag.  ','violetdusk.jpg','violetduskCU.jpg',0,1,6),
(285,'\"Sun-Kissed\" (SOLD)',38,'<font color=red>Sorry, this bag has been purchased.</font>Shipping to Canada/continental USA included in price. Worldwide shipping is available!  Bright and vibrant!  This bag features energizing bursts of colour.  100% cotton exterior featuring a blooming floral motif with dragonflies and other surprises hidden within. This yoga bag is the perfect way to carry your yoga gear, with a large main compartment to carry more than just your mat! Spacious drawstring opening, 2 pockets, a place to clip your keys, a wide strap for comfort, fully lined with coordinating fabric and finished off with decorative beading. Measures approximately 30\" high x 14\" wide x 8\" base. Second photo shows inside of the bag. ','sunkissed.jpg','sunkissedCU.jpg',0,1,7),
(344,'\"Water\" (SOLD)',18,'<font color=blue>Sorry, this necklace has been purchased.</font> \"Water\" in the Elemental series of one-of-a-kind, handcrafted necklaces. This necklace features the kanji symbol for \"water\", which is embraced on either side by a string of semi-precious gemstone beads. Measures approximately 18\" in length, with a 1\" extension chain secured with a lobster claw clasp and hook. See others in this series, including \"earth\", \"metal\" and \"wood\".','water.JPG','waterCU.JPG',0,4,8),
(346,'\"Om\" Sterling Silver (SOLD)',18,'<font color=blue>Please note, these earrings are a special purchase!  They are the only jewelry items that are not handcrafted. But I thought they were too nice to pass up! Click on the photo for a closer look at the detail!</font></i> \"Om\" ~ the ancient Hindu symbol is beautifully depicted in sterling silver! These gorgeous stud earrings measure approximately 3/8\" wide (just less than 1 cm). The earrings come mounted and packaged in a small gift box, ready to give!','omear.JPG','',0,4,16),
(343,'\"Wood\" Kanji Necklace',18,'\"Wood\" in the Elemental series of one-of-a-kind, handcrafted necklaces. This necklace features the kanji symbol for \"wood\", which is embraced on either side by a row of wooden beads. Measures approximately 18\" in length, with a 1\" extension chain secured with a lobster claw clasp and hook. See others in this series, including \"water\", \"metal\" and \"earth\".','wood.JPG','woodCU.JPG',0,4,6),
(342,'\"Earth\" Kanji Necklace',18,' \"Earth\" in the Elemental series of one-of-a-kind, handcrafted necklaces. This necklace features the kanji symbol for \"earth\", which is embraced on either side by a string of semi-precious gemstone beads. Measures approximately 18\" in length, with a 1\" extension chain secured with a lobster claw clasp and hook. See others in this series, including \"water\", \"metal\" and \"wood\".','earth.JPG','earthCU.JPG',0,4,4),
(288,' \"Barley\" Organic Cotton (SOLD',38,'<font color=red>Sorry, this item has been purchased.</font>Shipping to Canada/continental USA included in price. Worldwide shipping is available!  This yoga bag features a 100% ORGANIC cotton exterior with red detailing.  Take a peek inside to see a stunning golden green lining, matching inner pocket to keep small items handy, and a convenient key clip! Spacious drawstring opening and a wide strap for comfort, finished off with decorative beading on the drawstring to make this bag truly unique. Measures approximately 13\" wide x 31\" long, plenty of space to fit a standard yoga mat with room to spare for your accessories. ','barley.jpg','barleyIN.jpg',0,1,4),
(289,'\"Blue Dane\" Mat Bag (SOLD)',38,'<font color=blue>Sorry, this bag has been purchased.</font> Shipping to Canada/continental USA included in price. Worldwide shipping is available! This yoga bag features a cotton-blend exterior with a white, Danish woodstamped pattern throughout. Take a peek inside to see a matching soft blue lining to let your \"sticky\" mat slide in and out easily, an inner pocket to keep small items handy, and a convenient place to clip your keys! Spacious drawstring opening and a wide strap for comfort, finished off with decorative antique golden beads on the drawstring to make this bag truly unique. Measures approximately 12\" wide x 32\" long, plenty of space to fit a standard yoga mat with room to spare for your accessories. ','bluedane.jpg','bluedaneIN.jpg',0,1,3),
(290,'\"Geisha\" Tote',0,'The word Geisha literally translates to “arts person” (gei = art, sha = person), and describes what a Geisha is – a woman trained in the traditional arts of Japan, such as music, dance, and singing. \r\n\r\nThis one-of-a-kind tote features a beautiful, 100% cotton outer fabric, depicting Geishas playing instruments in a field of blossoming cherry trees. The tote measures approximately 12” long x 11” high x 3” wide, with wide straps for comfort. Take a close look, and you’ll see a twinkle of gold dust throughout this gorgeous fabric!  Beautifully detailed with pink satin ribbon on the front. Take a peek inside the bag and you will see a matching pocket to keep those small items from slipping to the bottom of the bag. A magnetic snap closure keeps your belongings secure. All beautifully lined in a stunning gold-green fabric. The bag will come with a description of the meaning of Geishas, as The Geisha Tote honors talented and artistic women around the world. You can purchase this bag as a gift for yourself, or another talented woman in your life. Shipping to Canada/continental USA included in price. Worldwide shipping is also available!\r\n','geishabag1.jpg','geishabag2.jpg',0,18,9),
(291,'\"Elle\" Purse',0,'<font color=red>Sorry, this item has been purchased. </font>  Elegant simplicity, without frills or fuss.  Classic striped purse in the season\'s best colours, lined with a gorgeous copper-coloured satin, and embellished with a simple bow.  Magnetic snap closure keeps your items secure.  This purse measures approximately 9\" x 7\" x 3\".  Shipping to Canada/continental USA included in price. Worldwide shipping is also available!','stripetote.jpg','stripetoteIN.jpg',0,18,8),
(292,'\"Om\" Tote (SOLD)',32,'<font color=red>This bag has been purchased.</font> This beautiful bag depicts the Hindu symbol \"Om\" on the front pocket.  Made from 100% cotton corduroy, the bag is lined with a matching indigo poly lining.  Wide straps for comfort, and a magnetic snap closure to keep your items secure.  Bag measures approximately 10\" x 11\" x 3\".  Shipping to Canada/continental USA included in price. Worldwide shipping is also available!','omtote.jpg','omtoteIN.jpg',0,3,12),
(293,'\"Downward Dog\" Hemp Tote',32,'This beautiful bag depicts the yoga pose, \"Downward Dog\", embroidered on the front pocket. Made from 100% hemp canvas, the bag is lined with a matching 100% cotton batik lining. Wide straps for comfort, and a magnetic snap closure to keep your items secure.  Bag measures approximately 12\" x 11\" x 3\".  Shipping to Canada/continental USA included in price. Worldwide shipping is also available!','downdogtote.jpg','downdogtoteIN.jpg',0,3,5),
(294,'\"Harvest\" Set',0,'<font color=red>Sorry, this set has been purchased.  Please contact me for custom-made pieces.</font>This necklace and bracelet set features an 18\" necklace and a tension mounted wire bracelet which wraps around the wrist (one size fits most).  The necklace also has a 1\" extension chain so that you can adjust the length easily using the lobster claw clasp and hook closure.  High quality beads were used to create this one-of-a-kind set.   Shipping to Canada/continental USA included in price.  Will ship worldwide!','harvest.JPG','harvestCU.JPG',0,18,12),
(295,'\"Amber Sunset\"',0,'<font color=red>Sorry, this necklace set has been purchased.  Please contact me for custom-made pieces.</font>  This necklace and bracelet set features an 18\" necklace and a tension mounted wire bracelet (one size fits most) which wraps around the wrist. The necklace also has a 1\" extension chain so that you can easily adjust the length using the lobster claw clasp and hook closure. High quality beads and spacers were used to create this one-of-a-kind set.  Shipping to Canada/continental USA included in price.  Will ship worldwide!','amberset.JPG','ambersetCU.JPG',0,18,12),
(296,'\"Rose Quartz\" Set',0,'This necklace and bracelet set features an 18\" necklace and a tension mounted wire bracelet (one size fits most) which wraps around the wrist. The necklace also has a 1\" extension chain so that you can easily adjust the length using the lobster claw clasp and hook closure. High quality, semi-precious Rose Quartz beads were used to create this one-of-a-kind set.  Shipping to Canada/continental USA included in price.  Will ship worldwide!','rosequart.JPG','rosequartzCU.JPG',0,18,8),
(297,'Set of 5 Produce Bags',18,'100% unbleached cotton produce bags. The environmentally friendly alternative to plastic bags for buying and storing your fruits and vegetables. These bags are also breathable, so moisture doesn’t get trapped causing mold and “slime”, as often happens with plastic bags. \r\nYou will receive 5 handcrafted bags (3 large, 2 small).  Shipping to Canada/continental USA included in price. Worldwide shipping is also available! *Please note: Bags come empty, and may not be exactly as shown in photo.','producebags.jpg','',0,3,11),
(298,'Mini Yoga Bag Keychain!',8,'These adorable yoga mat keychains are the perfect little gift for the yoga enthusiast in your life!  These bags arrive complete with a rolled up \"sticky\" mat inside!  They are made from leftover small pieces of fabric which would otherwise be disposed, so you never know which colour or pattern you\'ll get!  Each one is different and unique.  FREE shipping to Canada/Continental US!','minibag0001.JPG','miniyogabag.JPG',0,8,7),
(365,'\"Copper Dragon\"',18,'Dragon, a symbol of strength and good luck.  This necklace features a handpainted dragon on a ceramic bead.  High quality beads in tones of copper, gold and silver flank either side of the elegant dragon charm.  <p>Handcrafted and securely attached to a lobster clasp and loop. The necklace, measured from end-to-end is approximately 16\" long, with a 2\" extension chain to let you choose the length. <p>\r\n\r\nShipping to Canada/continental USA included in price. ','neckdragon.JPG','neckdragonCU.JPG',0,4,1),
(354,'\"Retro Dots\" Purse',22,'This bag has been carefully handcrafted using 100% cotton fabric. The outside features geometric dots in shades of green, while the real beauty lies within the bag. Take a peek inside, and you will see that this bag is lined with vintage fabric, with a whimsical print of butterflies and florals! This bag has been constructed with interfacing for durability and form, with careful attention to topstitched detailing for a polished and stylish look. It measures approximately 7\"x7\"x2\" with 14\" handles. A magnetic snap closure keeps your belongings secure. ','purse-tote-vintage-bag.jpg','purse-tote-vintage-in.jpg',0,3,10),
(311,'Mini Yoga Magnets - set of 3',4,'Cute as a button!  Strong, 1/2\" magnets from your favourite online yoga supplier ;) FREE shipping to Canada/Continental US!','minimagnets0002.JPG','',0,8,8),
(324,'Green Drawstring Gift Bag',5,'A roomy, drawstring bag.  Perfect for gift-giving, or for keeping a child\'s toys in one place for home storage or travel!  Measures approximately 11\" x 21\".  Decorative beads on drawstring.  Not recommended for children 3 and under, due to small parts.','baggiftgreen2.jpg','',0,14,9),
(341,'Custom Backpack',0,'This diaper bag was custom-made according to my client\'s specifications for size and features.  A zippered outer pocket, a divider inside with ample pocket space for various items such as baby toys and diapers.  This bag also included a keyclip and magnetic snap closure on the flap of the bag.  A zippered \"wet bag\" completed the set.  ','shannonsbag5.jpg','shannonsbag2.jpg',0,18,18),
(323,'Green Drawstring Gift Bag',5,'A roomy, drawstring bag.  Perfect for gift-giving, or for keeping a child\'s toys in one place for home storage or travel!  Measures approximately 11\" x 21\".  Decorative beads on drawstring.  Not recommended for children 3 and under, due to small parts.','baggiftgreen.jpg','',0,14,8),
(315,'Gift Baskets, Custom-made!',0,'You choose the price of the gift basket, and let me know the \"theme\", and I will do the rest!  I have created baskets of gifts for baby showers, birthdays, co-workers, weddings, anniversaries, graduations, thank-you gifts and more! Can be sent/delivered to you, or directly to the recipient.  Gift-giving has never been easier.  Perfect for any occasion and all budgets! ','elainegiftbasket 002.jpg','elainegiftbasket 007.jpg',0,21,1),
(316,'Faux Suede Messenger Bag',0,'<font color=red>Sorry, this item has been purchased.</font>  This gorgeous bag is made of a luxurious brown faux suede fabric, and lined in 100% cotton.  The bag features a large main compartment, a large flat pocket on the front, and a small pocket inside to keep small items like keys and credit cards handy.  The flap of the bag closes with a magnetic snap to keep your items secure. Measures approx. 17”x12”x3”. The strap is completely adjustable for that perfect fit!Carefully handcrafted with attention to detail and design.  This bag is truly unique and functional!  (Comes empty. Shown in second photo filled with large texts to illustrate how roomy this bag is!).\r\n\r\n \r\n\r\n \r\n\r\n','suedebag1.jpg','suedebag4.jpg',0,18,7),
(328,'Giraffe Drawstring Gift Bag',5,'A roomy, drawstring bag featuring adorable giraffes! Perfect for gift-giving, or for keeping a child\'s toys in one place for home storage or travel! Measures approximately 10\" x 19\". Decorative beads on drawstring. Not recommended for children 3 and under, due to small parts.','baggiftgiraffe.jpg','',0,14,10),
(329,'Blue Drawstring Gift Bag',5,'A roomy, drawstring bag featuring fish, boats, starfish, kites and more! Perfect for gift-giving, or for keeping a child\'s toys in one place for home storage or travel! Measures approximately 11\" x 14\". Decorative beads on drawstring. Not recommended for children 3 and under, due to small parts.','baggiftblue.jpg','',0,14,11),
(363,'\"Green Tea\" necklace',18,'Take a sip of green tea, and your tastebuds immediately respond to the unique fragrant flavour.  As you cradle the cup of tea in your hands and let the warmth take over, you are left with a feeling of health and vitality.  <p>That is the feeling I was trying to capture when I created this necklace.  Each bead was hand chosen and carefully placed in a specific sequence to create a beautiful and unique necklace.  The large bead at the centre is smooth to the touch, just as the perfect cup of tea is soothing to the soul. \r\n\r\n<p>Handcrafted using high quality beads on a strong wire, securely attached to a lobster clasp and loop.  The necklace, measured from end-to-end is approximately 17.5\" long, with a 2\" extension chain to let you choose the length. <p>Shipping to Canada/continental USA included in price. Will ship worldwide!\r\n','neckgreen.jpg','neckgreenCU.jpg',0,4,2),
(369,'\"Blue Bird\" (matte)',20,'This little birdie is the bringer of good news! Do you have some exciting news to share with a loved one? Celebrating a special event? This little bird will carry your message in style, specially gift-wrapped and personalized with a note of your choice!  <p>\r\nHandcrafted using high quality beads on a strong wire, securely attached to a lobster claw clasp. The necklace, measured from end-to-end is approximately 20\" long, with a 2\" extension chain to let you choose the length!\r\n<p>\r\nShipping to Canada/continental USA included in price. \r\n','neckbirdmatte.JPG','neckbirdmatteCU.JPG',0,4,3),
(372,'Gift Certificates',0,'Gift certificates may be purchased in any denomination!  Either a hard-copy gift certificate will be mailed to the recipient, or if it\'s a last minute gift that needs to get there QUICK, an online gift certificate will be e-mailed. Each gift certificate is sent with your own personalized message, and anonymous gift-giving may also be arranged. How\'s that for good karma? ;)  FREE SHIPPING TO US/CANADA!','','',0,22,1);
/*!40000 ALTER TABLE `products` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Dumping events for database 'anayoga_anayoga'
--

--
-- Dumping routines for database 'anayoga_anayoga'
--
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*M!100616 SET NOTE_VERBOSITY=@OLD_NOTE_VERBOSITY */;

-- Dump completed on 2026-09-19 13:37:28
